### PR TITLE
Added support to filter events by ID

### PR DESCRIPTION
**Pull request by jbrandligt**
Hi Jeroen,

I figured I could add this feature my self. Hope you can approve of it. 

Cheers

### CODE REVIEW

**Comment by slimndap** [comment]
Nice!

The automatic tests are failing, so we'll need to look into this first.

**Comment by jbrandligt** [comment]
Didn't look at the test files, I see I have to add some stuff there too to pass the tests.

**Comment by slimndap** [comment]
It would also be nice if we support `post__not_in`.

**Comment by jbrandligt** [comment]
I thought about that, I wasn't sure if that would be useful for events. But I will add it.

**Comment by slimndap** [comment]
I merged everything (and fixed the failing test).

**Comment by jbrandligt** [comment]
Cool, so post__not_in is added too now?

**Comment by slimndap** [comment]
Yes. It will be part of the next minor release (v0.11.8). Somewhere this week.

**Comment by jbrandligt** [comment]
Ok, because I still see a build error on the post__not_in addition... or is that fixed too

**Comment by slimndap** [comment]
I just released v0.11.8.

**Comment by jbrandligt** [comment]
Awesome!

**Comment by jbrandligt** [comment]
Jeroen, I did another small customization to the post__in event list option, but before I create a new pull request, it might be smart to discuss with you first. When I specify the post__in option it would make more sense if the sort order is changed to the order the event id's are listed. I would really like it to work this way. I made a small customization to wpt_order.php to achieve this. If you agree this makes sense I will create a new pull request.

**Comment by slimndap** [comment]
That depends on your the customisation.

I would like the `wpt_order` class to remain as simple as possible, because it has effect on a lot of places. It is probably better to hook into the `pre_get_posts` filter from your functions.php. You can use it to override the 'orderby' argument of your queries that use the `post__in` filter.

**Comment by jbrandligt** [comment]
Ok, no problem. I will look and see if I can get it done that way.

**Comment by jbrandligt** [comment]
Works like a charm. For anyone interested, just put this in your functions.php, (preferably in a child theme) to change the sort order of events to the order they are listed in the post__in argument:

add_action( 'pre_get_posts', 'custom_get_posts' );
function custom_get_posts( $query ) {
  if($query->get('post__in')) {    
    $query->set('orderby','post__in');
  }
}

**Pull request closed without merging**
