### PR TITLE
Updated German translation

### PR DESCRIPTION
**Pull request by henk23**

### CODE REVIEW

**Comment by slimndap** [comment]
Thank you!

Not sure, but could it be that 'Seasons' is not translated correctly?

```
+msgid "Seasons"
+msgstr "Spielzeiten"
```

Shouldn't it be 'Saisons'?

**Comment by henk23** [comment]
Hi,

nope, It’s correct. Saisons is not used in the theatre context.

Thank you for the great plugin!

I noticed another mistake I made:

#: functions/wpt_setup.php:114
msgctxt "slug"
msgid "production"
msgstr "Produktion“

The slug should be lowercase „produktion".

And something I did not find a solution for: The datetimepicker does not localize.
The internationalization is in the code, but it shows the english version.

Best
Heiko

> Am 23.06.2015 um 22:27 schrieb Jeroen Schmit <notifications@github.com>:
> 
> Thank you!
> 
> Not sure, but could it be that 'Seasons' is not translated correctly?
> 
> +msgid "Seasons"
> +msgstr "Spielzeiten"
> Shouldn't it be 'Saisons'?

**Comment by slimndap** [comment]
Localising the datetimepicker would require passing the current Wordpress language through javascript. Not possible right now, but I will add it as a feature request.

Are you using the plugin for something cool?

**Comment by henk23** [comment]
Wouldn’t it be possible to do a quick-and-dirty solution for now? Something like

<script>

var wp_lang = <?php echo $wp_lang; ?>

</script>

I’m redoing a theatre website, which is 10 years old… They don’t even have a database yet, everything is text-based in joomla. ^^

I have a few other feature requests for you ;)

- Option to define default options for city and venue - in my case it will be the same 95% of time…
- Option to define which event fields are used - I won’t need all the ticket fields and the end time.

To many fields to confuse the people who will work with it. ^^
My goal is to make it as easy as possible to use for my clients.

> Localising the datetimepicker would require passing the current Wordpress language through javascript. Not possible right now, but I will add it as a feature request.
> Are you using the plugin for something cool?

**Comment by slimndap** [comment]
Can start new issues for these questions, so we can discuss them seperately?

**Comment by slimndap** [comment]
I just release v0.12 with your updated German translation. Thank you!

Welcome to the club:
https://github.com/slimndap/wp-theatre/graphs/contributors

**Comment by henk23** [comment]
Awesome! Thanks! I will have to review it. I noticed some of the translations are not totally accurate when I saw them in context.

**Comment by slimndap** [comment]
Hi!

Would be interested in being in charge of the German translation of the Theater for WordPress plugin?
See: https://translate.wordpress.org/locale/de/default/wp-plugins/theatre

**Comment by slimndap** [comment]
Yes it is. I asked someone else to do it a couple of weeks ago.
However, if you see any mistakes, it would be great if you can still submit them.

**Pull request closed without merging**
