### PR TITLE
Prevent save event loop

### PR DESCRIPTION
**Pull request by joostdekeijzer**
Just as done in `WPT_Event_Editor::save_event` the `save_post` action must be temporarily disabled here.

### CODE REVIEW

**Comment by slimndap** [comment]
Could this also be a fix for #221?

**Comment by slimndap** [comment]
Can you describe the exact problem that this change resolves?

**Comment by joostdekeijzer** [comment]
I'm making an extension that saves post data from a custom field added to wp_theatre_event.

Creating a new event (from the Production screen) works fine because `WPT_Event_Editor::save_event` prevents the loop.

Modifying an event creates an infinite loop this PR fixes.

**Comment by joostdekeijzer** [comment]
The post_type check is most important, by the way (added in the 3rd and 4th commits)

**Comment by joostdekeijzer** [comment]
Don't think this has anything to do with #221

**Comment by slimndap** [comment]
Can you describe the exact steps I should take to end up in the infinite loop?
When I add an event and then try to edit it, everything seems to work fine in the current release.

**Comment by joostdekeijzer** [comment]
I see now that my PR changes are unneeded complex. Only the change in lines 252-254 are needed. I'll simplefy the PR today.

To get an infinite loop:

1. Add custom field to event using `wpt/event_editor/fields` filter. Custom field needs a custom save callback.
2. In the save callback, create a post/page/product/whatever (I'm creating a product)
3. Go to **edit** an event in the WordPress backend (create uses different class and logic where the issue doesn't arise)
4. Save -> loop!

The issue is that `WPT_Event_Admin:: save_event` does not check the post_type of the saved item, so it does it's logic on any post_type that is saved. This results in the infinite loop when creating a post during saving an event.

**Pull request merged**
