### PR TITLE
Add endtime field to wpt_events

### PR DESCRIPTION
**Pull request by jbrandligt**

### CODE REVIEW

**Comment by jbrandligt** [comment]
Hey, I did a partial commit of my work so far. Could you have a look and tell me if this is what you had in mind?

**Comment by slimndap** [comment]
And yes: this is what I had in mind.

**Comment by jbrandligt** [comment]
Ok cool, I'll clean up the code and implement the date methods too then.

**Comment by slimndap** [comment]
I just merged your code back into mine.

**Comment by jbrandligt** [comment]
Sweet!

**Comment by slimndap** [comment]
Welcome to the club: https://github.com/slimndap/wp-theatre/graphs/contributors

**Pull request closed without merging**
